//go:generate go-enum --names --values --lower --flag

package cmd

import (
	"strings"

	"github.com/spf13/cobra"

	"github.com/ttl256/euivator/pkg/hwaddr"
)

// ENUM(COLON, DASH, DOT, PLAIN).
type EUIFormat string //nolint: recvcheck // generated by a third-party

var flagEUIFormat = EUIFormatCOLON // default formatting

var convertFuncMap = map[EUIFormat]func([]byte) string{
	EUIFormatCOLON: hwaddr.AsColon,
	EUIFormatDASH:  hwaddr.AsDash,
	EUIFormatDOT:   hwaddr.AsDot,
	EUIFormatPLAIN: hwaddr.AsPlain,
}

var euiCmd = &cobra.Command{
	Use:   "eui",
	Short: "Common operations on EUIs",
}

func init() {
	rootCmd.AddCommand(euiCmd)
	euiCmd.PersistentFlags().Var(
		&flagEUIFormat,
		"format",
		"permitted options: "+strings.Join(EUIFormatNames(), ", ")+" (case insensitive)",
	)
}
