name: Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit:
    strategy:
      matrix:
        os: [ubuntu-22.04]
    runs-on: ubuntu-latest
    steps:
      - name: dummy
        run: echo start
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: tidy
        run: |
          make audit/tidy
      - name: verify-deps
        run: |
          make audit/verify-deps
      - name: lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.63.4
      - name: test
        run: |
          make test
      - name: build
        run: |
          make build
      - run: ./bin/euivator --version
      - run: ./bin/euivator --help
